on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - uses: actions/checkout@v1
      - run: Rscript -e 'BiocManager::install("BiocCheck")'
      - run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'
      - run: cd .. && R CMD BiocCheck rRPMM